### ISSUE TITLE
Capture request timing information?

### ISSUE THREAD

**Issue by gitblit** [cybercoder-naj/logestic#10]
This looks like a very nice addition the login ecosystem. Congrats!

Would it be difficult to capture request timing? I'd love to be able to log the duration of request handling/processing just by adding a library. I'm aware of the server-timing plugin, but I'm really interested to capture this in logs, not in response headers.

**Comment by cybercoder-naj** [comment]
Should not be a difficult task. It was on my mind while developing it. Thanks!

**Comment by cybercoder-naj** [comment]
Thanks for the request, has been merged and deployed with v1.0.0-alpha.5

**Comment by gitblit** [comment]
Woohoo! Perfect, thank you!
