### ISSUE TITLE
Consider optional onRequest format hook

### ISSUE THREAD

**Issue by gitblit** [cybercoder-naj/logestic#13]
With my custom logging, I have an `onRequest` hook that logs start of request processing. This is handy in the case where Elysia (or a plugin) does something unexpected and the request does not make it all the way through to `onResponse`. It would be convenient if there was an optional `format` override for `onRequest`, maybe by default it does nothing.

This is a hybrid of what I am using and what I'd like to have.

```javascript
// exports a Logestic plugin instance
export const logger = new Logestic()
  .use(["time", "method", "path", "status", "duration"])
  .format({
    onRequest({ time, method, path }) {
      const grayTime = chalk.gray(`${time!!.toISOString()}`);
      const methodPath = chalk.cyan(`${method} ${path}`);

      return `[${grayTime}] 🟢 ${methodPath}`;
    },    
    onSuccess({ time, method, path, status, duration }) {
      const grayTime = chalk.gray(`${time!!.toISOString()}`);
      const methodPath = chalk.cyan(`${method} ${path}`);
      let statusColor = chalk.white;

      if (200 <= status && status < 300) statusColor = chalk.green;
      if (400 <= status && status < 500) statusColor = chalk.yellow;
      if (500 <= status) statusColor = chalk.red;

      const durationInMsecs = chalk.magenta(`${(duration ?? 0n) / 1000n}`);

      return `[${grayTime}] 🛑 ${methodPath} | ${statusColor(status)} | ${durationInMsecs} ms\n`;
    },
    onFailure({ request, error, code, datetime }) {
      const log = chalk.red(`[${datetime.toISOString()}]: ${request.method} ${request.url} | ERROR | ${code}`);
      return `${log}\n${error}`;
    },
  });
```

**Comment by cybercoder-naj** [comment]
Sounds like a reasonable addition. Will focus on it once the stable version has been released. Are there any major/minor bugs you've encountered?

**Comment by gitblit** [comment]
I did encounter a bug when first using the sample for a custom logger. Your example logs to a file. I just copied & pasted what you had and ran it. This caused errors because the destination log file did not exist, which seemed a surprising error. I didn't chase that, I just removed the destination file config.

I am liking your library very much. :+1: It's a needed option for the Elysia community.

**Comment by cybercoder-naj** [comment]
Implement. Ready to publish

**Comment by gitblit** [comment]
Awesome! I’m away for the week but will check this out next week!

**Comment by gitblit** [comment]
`onRequest` works great! Unfortunately, `onSuccess` breaks for me with the above customized logger with the change in 1.0.1.

**Comment by gitblit** [comment]
Reported in #20
