### ISSUE TITLE
It breaks on Elysia 1.1.0

### ISSUE THREAD

**Issue by wladpaiva** [cybercoder-naj/logestic#31]
### What version of Logestic are you using?

1.2.0

### What is the bug and how to reproduce it?

Elysia just released the 1.1.0 and logestic breaks on it.

![Screenshot 2024-07-16 at 09 30 32](https://github.com/user-attachments/assets/bd7008f1-2c80-456b-9e8c-4c45418df4d3)

**Comment by cybercoder-naj** [comment]
Thanks for reporting. Will look into it 👀

**Comment by cybercoder-naj** [comment]
I am going to wait for a couple of days before merging in the patched version since it seems elysia is slightly unstable with the new releases today.

**Comment by cybercoder-naj** [comment]
Please create a new issue if Logestic still breaks Elysia. Thanks!
